lambdaclass/lambda_ethereum_consensus

.github/CODEOWNERS, .github/pull_request_template.md, .github/workflows/lint-pr-title.yml
Add conventions:
- conventional commits
- require codeowners
- pull request template
=> chore: Add repository conventions and basic configurations.

.tool-versions, README.md, mix.exs
**Motivation**
Adding tool-versions so that we have fixed versions of every requirement
Closes #15
=> build: add `.tool-versions`.

README.md
**Motivation**
Add an explanation of why we use the Elixir programming language in our project, it has been asked many times.
Added a why Elixir section in the Readme and explained why in my humble opinion we are using Elixir in this project.
=> docs: add why Elixir?

README.md
**Motivation**
Added a Contributor Package to help onboarding newcomers willing to contribute to the project.
It helps by providing quick start guide, interesting foundational knowledge resources, issue organisation, pr formats, communication means.
=> docs: added contributor package

lib/ssz_types/voluntary_exit.ex, native/ssz_nif/src/lib.rs, native/ssz_nif/src/types/beacon_chain.rs, native/ssz_nif/src/utils/mod.rs, test/spec/runners/ssz_static.ex
This PR adds the VoluntaryExit SSZ container
=> feat: add beacon-chain spec containers (VoluntaryExit)

lib/ssz_types/deposit_data.ex, native/libp2p_nif/go.sum, native/ssz_nif/src/lib.rs, native/ssz_nif/src/types/beacon_chain.rs, native/ssz_nif/src/utils/from_elx.rs, native/ssz_nif/src/utils/from_lh.rs, test/spec/runners/ssz_static.ex
This issue is to adding the DepositData SSZ container
Closes #52
=> feat: add DepositData SSZ container

README.md
**Motivation**
To make sure that we are fostering a positive community and Project added a Code of Conduct
Inspired by [Contributor Convenant 2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)
=> docs: added code of conduct

README.md
**Motivation**
Improving the contributor package to add information related to support, CoC and others
Structure and information improvements
=> docs: improve contributor package

lib/ssz_types/deposit_message.ex, native/ssz_nif/src/lib.rs, native/ssz_nif/src/types/beacon_chain.rs, test/spec/runners/ssz_static.ex
This issue adds the DepositMessage SSZ container
Closes #51
=> feat: add DepositMessage SSZ container

lib/ssz_types/indexed_attestation_mainnet.ex, native/ssz_nif/src/elx_types/beacon_chain.rs, native/ssz_nif/src/lib.rs, native/ssz_nif/src/ssz_types/beacon_chain.rs, native/ssz_nif/src/utils/from_elx.rs, native/ssz_nif/src/utils/from_ssz.rs, test/spec/runners/ssz_static.ex
=> feat: add `IndexedAttestation` SSZ container

lib/ssz_types/signed_voluntary_exit.ex, native/ssz_nif/src/elx_types/beacon_chain.rs, native/ssz_nif/src/lib.rs, native/ssz_nif/src/ssz_types/beacon_chain.rs, test/spec/runners/ssz_static.ex
**Motivation**
Implements the signed voluntary exit container.
Closes #70
=> feat: add signed voluntary exit container

lib/ssz_types/signed_beacon_block_header.ex, native/ssz_nif/src/elx_types/beacon_chain.rs, native/ssz_nif/src/lib.rs, native/ssz_nif/src/ssz_types/beacon_chain.rs, test/spec/runners/ssz_static.ex
Add `SignedBeaconBlockHeader` SSZ type.
Closes #72
=> feat: add `SignedBeaconBlockHeader` SSZ type.

lib/ssz_types/attester_slashing.ex, native/ssz_nif/src/elx_types/beacon_chain.rs, native/ssz_nif/src/lib.rs, native/ssz_nif/src/ssz_types/beacon_chain.rs, test/spec/runners/ssz_static.ex
**Motivation**
Implements the attester slashing container.
Closes #63
=> feat: add attester slashing container

lib/ssz_types/mod.ex, lib/ssz_types/sync_aggregate.ex, native/ssz_nif/src/elx_types/beacon_chain.rs, native/ssz_nif/src/lib.rs, native/ssz_nif/src/ssz_types/beacon_chain.rs, test/spec/configs/minimal.ex, test/spec/runners/ssz_static.ex
**Motivation**
Implements the SyncAggregate container type.
Closes #73
=> feat: add sync aggregate type

native/ssz_nif/src/lib.rs, native/ssz_nif/src/utils/helpers.rs, native/ssz_nif/src/utils/mod.rs, test/unit/ssz_test.exs
=> feat: improve "undefined schema" error message

.github/workflows/ci.yml, README.md
**Motivation**
Make the learning section more useful 
Added some useful links, and reorganised the sections a little bit. I tried to reorder the sections to have the short introductory links at the top and the longer and more profound ones at the bottom.
Also created a separate section for the Consensus part. I suspect that most people getting into this repo already know the basics about Ethereum. 
Finally, I emphasised the Eth2 book, which is the main resource to be able to start working on this repo.
=> docs: add some more reading material and reorder links.

lib/ssz_types/sync_committee.ex, native/ssz_nif/src/elx_types/beacon_chain.rs, native/ssz_nif/src/lib.rs, native/ssz_nif/src/ssz_types/beacon_chain.rs, test/spec/configs/minimal.ex, test/spec/runners/ssz_static.ex
**Motivation**
add `SyncCommittee` SSZ container
Needed for the implementation of the `BeaconState` SSZ Container #69 
Closes #74
=> feat: add `SyncCommittee` SSZ container

lib/bls.ex, native/bls_nif/src/lib.rs, test/spec/runners/bls.ex
Description
Add bls eth_fast_aggregate_verify function by using the lighthouse implementation
Closes #137
=> feat: add BLS `eth_fast_aggregate_verify` function

README.md
**Motivation**
2 links were dead, updated them
yellow paper youtube video + elixir blog
=> docs: updated dead links

lib/bls.ex, native/bls_nif/src/lib.rs, test/spec/runners/bls.ex
Implements the BLS signature verification. 
Closes #132
=> feat: add BLS verify

native/libp2p_nif/main.go
This PR adds more options specified to the libp2p constructors by default. These were taken from the Prysm codebase.
=> feat: specify more options by default

lib/ssz.ex, native/ssz_nif/README.md, native/ssz_nif/src/lib.rs, native/ssz_nif/src/utils/helpers.rs, native/ssz_nif/src/utils/mod.rs, test/unit/ssz_test.exs
Addresses #220 (doesn't fully solve it, as only lists are supported)
=> feat(ssz): list serialization and hashing

lib/ssz_types/p2p/metadata.ex, native/ssz_nif/src/elx_types/p2p.rs, native/ssz_nif/src/ssz_types/config.rs, native/ssz_nif/src/ssz_types/p2p.rs, native/ssz_nif/src/utils/mod.rs, test/unit/ssz_test.exs
**Motivation**
Add `Metadata` SSZ container + unit test
Closes #191
=> feat: add `Metadata` SSZ container + unit test

test/spec/runners/bls.ex, test/spec/runners/operations/runner.ex, test/spec/runners/ssz_static.ex, test/spec/utils/runner_behaviour.ex, test/spec/utils/testcase.ex
This should officialize the behaviour of the test runner modules, and give us a single point of documentation.
=> test: add `TestRunner` behaviour

lib/lambda_ethereum_consensus/application.ex, lib/lambda_ethereum_consensus/p2p/block_consumer.ex, lib/lambda_ethereum_consensus/p2p/block_downloader.ex, lib/lambda_ethereum_consensus/p2p/gossip_handler.ex, lib/lambda_ethereum_consensus/p2p/incoming_request_handler.ex, lib/lambda_ethereum_consensus/p2p/peer_consumer.ex, lib/lambda_ethereum_consensus/p2p/peerbook.ex, lib/lambda_ethereum_consensus/p2p/utils.ex, lib/libp2p/libp2p_stream.ex, lib/ssz_types/p2p/beacon_blocks_by_range_request.ex, test/unit/helper_test.exs, test/unit/libp2p_test.exs, test/unit/p2p_test.exs
Closes #208
Currently, the process requests a random block from a random peer and stores it in the database.
=> feat: request blocks from peers

lib/lambda_ethereum_consensus/application.ex, lib/lambda_ethereum_consensus/p2p/block_downloader.ex, lib/lambda_ethereum_consensus/p2p/peerbook.ex, lib/lambda_ethereum_consensus/store/block_store.ex, lib/lambda_ethereum_consensus/store/db.ex, lib/lambda_ethereum_consensus/store/state_store.ex, lib/lambda_ethereum_consensus/utils.ex
=> feat: integrate checkpoint sync with block requesting

native/libp2p_nif/go_src/main.go
Since we are moving to ports, we should comment these out.
=> chore: comment error prints in libp2p NIF

test/spec/runners/epoch_processing.ex, test/spec/runners/operations/runner.ex, test/spec/runners/operations/utils.ex, test/spec/utils/generator.ex, test/spec/utils/utils.ex
**Motivation**
Adding the test runner will unblock implementing transition functions
=> test: add epoch processing spec test runner.

lib/lambda_ethereum_consensus/application.ex, lib/lambda_ethereum_consensus/p2p/block_consumer.ex, lib/lambda_ethereum_consensus/p2p/gossip_handler.ex
Quick improvement of logs for display purposes. Also, making them debug logs.
=> chore: improve logs

.formatter.exs, lib/lambda_ethereum_consensus/p2p/incoming_request_handler.ex
**Motivation**
Let's make the logging less spammy
=> chore: improve logging for incoming requests handler.

lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex
=> fix: fixed bug in process_eth1_data_reset

lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, test/spec/runners/epoch_processing.ex
I somehow broke my zsh couldn't be able to test it yet before merging please wait so I can resolve the issue and execute the tests or please don't merge without executing the test 
Closes #265
=> feat: process participation flag updates

lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, lib/lambda_ethereum_consensus/state_transition/misc.ex, lib/lambda_ethereum_consensus/state_transition/predicates.ex
**Motivation**
Cleanup and refactor of the state transition functions to follow correct file structure.
=> refactor: refactor of the state transition functions

Makefile, lib/lambda_ethereum_consensus/application.ex, lib/lambda_ethereum_consensus/beacon/pending_blocks.ex, lib/lambda_ethereum_consensus/fork_choice/store.ex, lib/lambda_ethereum_consensus/fork_choice/supervisor.ex, lib/lambda_ethereum_consensus/fork_choice/utils.ex, lib/lambda_ethereum_consensus/p2p/gossip_handler.ex, lib/lambda_ethereum_consensus/state_transition/misc.ex, lib/ssz_types/store.ex, test/unit/pending_blocks_test.exs
We need to add the initial block that corresponds to the beacon state that we got from the checkpoint sync. From that point on we can rely on the pending blocks genserver to fill all the blocks from checkpoint to now
=> feat: download initial finalized block and add pending blocks to fork choice.

lib/lambda_ethereum_consensus/p2p/subscriber.ex, lib/libp2p_port.ex, native/libp2p_port/internal/proto_helpers/proto_helpers.go, native/libp2p_port/internal/reqresp/reqresp.go, native/libp2p_port/internal/subscriptions/subscriptions.go, native/libp2p_port/main.go, proto/libp2p.proto, test/unit/libp2p_port_test.exs
=> feat: add gossip validator

metrics/docker-compose.yml
See https://github.com/grafana/grafana/issues/54942
Some of them were updated, so I changed them to official ones.
=> chore: change grafana and prometheus docker images

lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, lib/spec/runners/epoch_processing.ex, lib/ssz.ex, lib/ssz_types/root.ex, native/ssz_nif/src/elx_types/mod.rs, native/ssz_nif/src/lib.rs, native/ssz_nif/src/ssz_types/mod.rs, native/ssz_nif/src/utils/helpers.rs, native/ssz_nif/src/utils/mod.rs
=> feat: add `process_historical_summaries_update`

lib/utils/diff.ex, test/unit/diff_test.exs
=> feat: functions for struct comparisons

README.md
**Motivation**
a smol typo fix
=> fix: typo fix in readme

lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/fork_choice/store.ex, lib/ssz_types/store.ex, test/unit/diff_test.exs, test/unit/fork_choice/handlers_test.exs
=> feat: add `on_tick` handler

lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/telemetry.ex, metrics/grafana/provisioning/dashboards/home.json
~Depends on #381~
Image of the new vis:
=> feat: add sync progress graph

lib/utils/bit_vector.ex, test/unit/bit_vector_test.exs
=> feat: add bitvector module

lib/constants.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, lib/spec/runners/operations.ex
=> feat: added process_voluntary_exit

lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/fork_choice/store.ex, lib/lambda_ethereum_consensus/p2p/gossip_handler.ex, lib/lambda_ethereum_consensus/state_transition/state_transition.ex, lib/lambda_ethereum_consensus/utils.ex
=> feat: add `on_attestation` handler

lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/fork_choice/store.ex
=> feat: add `on_attester_slashing` handler

lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, lib/lambda_ethereum_consensus/state_transition/state_transition.ex, lib/spec/runners/epoch_processing.ex, lib/ssz_types/beacon_chain/beacon_state.ex
=> feat(epoch_processing): add `process_rewards_and_penalties`

lib/lambda_ethereum_consensus/state_transition/state_transition.ex
Since most of the functions are still a WIP, it just adds the commented glue code.
=> feat: implement `process_block`

config/config.exs, lib/lambda_ethereum_consensus/beacon/pending_blocks.ex, lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/fork_choice/store.ex, test/unit/pending_blocks_test.exs
**Motivation**
We want to store a reference to invalid blocks so that we don't try to download them or descendants indefinitely.
=> feat: store invalid blocks to make sure we don't download it indefinitely.

lib/constants.ex, lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/fork_choice/store.ex, lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, lib/lambda_ethereum_consensus/state_transition/misc.ex, lib/lambda_ethereum_consensus/state_transition/predicates.ex, lib/lambda_ethereum_consensus/state_transition/state_transition.ex, lib/spec/runners/fork_choice.ex
Since we weren't running any tests, some bugs slipped in. Commenting some validations on state transition I managed to check that the general workflow works.
=> fix: various handler errors

lib/lambda_ethereum_consensus/state_transition/state_transition.ex, lib/mix/tasks/generate_spec_tests.ex, lib/spec/runners/sanity.ex
Added spec test runner for sanity blocks and slots.
Closes #428 #429
=> test: add sanity spec tests runner

lib/constants.ex, lib/lambda_ethereum_consensus/state_transition/misc.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, lib/ssz.ex, lib/ssz_types/epoch.ex, native/ssz_nif/src/elx_types/mod.rs, native/ssz_nif/src/ssz_types/mod.rs, native/ssz_nif/src/utils/mod.rs, test/unit/ssz_test.exs
**Motivation**
block processing implement process_randao
Closes #437
=> feat: block processing implement process_randao

lib/lambda_ethereum_consensus/p2p/block_downloader.ex, lib/lambda_ethereum_consensus/telemetry.ex, metrics/grafana/provisioning/dashboards/home.json, native/libp2p_port/internal/reqresp/reqresp.go
=> feat: add block downloading rate gauge in Grafana

lib/constants.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, lib/spec/runners/operations.ex
Added `process_block_header`
Closes #302
=> feat: added `process_block_header`

lib/spec/runners/fork_choice.ex
**Motivation**
This will make it easier to work on fork choice tests
=> chore: divide fork choice tests by handlers.

lib/lambda_ethereum_consensus/state_transition/operations.ex
**Motivation**
implement block processing eth1 data
Closes #443
=> feat: implement block processing eth1 data

native/libp2p_port/internal/port/port.go, native/libp2p_port/internal/proto_helpers/proto_helpers.go, native/libp2p_port/internal/reqresp/reqresp.go, native/libp2p_port/main.go
This PR removes the bottleneck in `Libp2pPort` 🚀
=> feat: make `SendRequest` async

lib/spec/runners/finality.ex, lib/spec/runners/helpers/process_blocks.ex, lib/spec/runners/sanity.ex, lib/spec/runners/sync.ex
Added finality test runner
Added sync test runner
Closes #458 #461
=> test: add finality, sync tests and enable several sanity cases.

README.md
**Motivation**
The roadmap doesn't really reflect the state of the project. We should do a new one
=> docs: remove outdated roadmap

lib/spec/runners/random.ex
=> test: implement random test runner.

README.md
Fixes spec-test runner command
=> docs: fix spec-test runner command

lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex
=> perf: use ordered list indexing instead of `MapSet`

bench/byte_reversal.exs, lib/lambda_ethereum_consensus/cli.ex, lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, lib/utils/bit_vector.ex, test/unit/bit_vector_test.exs
=> fix: bitvector creation and serialization

lib/spec/runners/rewards.ex, lib/spec/utils.ex
=> feat: implement rewards spec test runner

lib/lambda_ethereum_consensus/application.ex, lib/lambda_ethereum_consensus/beacon/beacon_chain.ex, lib/lambda_ethereum_consensus/beacon/beacon_node.ex, lib/lambda_ethereum_consensus/beacon/checkpoint_sync.ex
**Motivation**
We need a bigger abstraction that has the current fork and controls which topics to subscribe to. Also it should store the information not directly related to the fork choice.
=> refactor: add beacon node supervisor.

lib/lambda_ethereum_consensus/fork_choice/store.ex, lib/lambda_ethereum_consensus/telemetry.ex, metrics/grafana/provisioning/dashboards/home.json
=> feat: add head's slot metric

lib/lambda_ethereum_consensus/beacon/beacon_chain.ex, lib/lambda_ethereum_consensus/beacon/beacon_node.ex, lib/lambda_ethereum_consensus/beacon/sync_blocks.ex, lib/lambda_ethereum_consensus/fork_choice/store.ex, lib/lambda_ethereum_consensus/p2p/gossip_handler.ex
**Motivation**
We want to move away from having store as a God object that stores all the data of the chain. This is a first step in that direction.
Moved the time calculation to beacon chain. This is a helper function used all over the place and should not be slowed down by block processing.
=> feat: add beacon chain with some data that was in fork choice.

lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/cache.ex, mix.exs, mix.lock
=> feat: clean up old cache entries

lib/chain_spec/chain_spec.ex, lib/lambda_ethereum_consensus/beacon/beacon_chain.ex, lib/lambda_ethereum_consensus/beacon/beacon_node.ex, lib/lambda_ethereum_consensus/p2p/block_downloader.ex, lib/lambda_ethereum_consensus/p2p/gossip/gossipsub.ex, lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex
**Motivation**
We need to compute fork digest dynamically to support multiple networks and forks.
Closes #554
=> fix: remove hardcoded fork digest values

.github/workflows/ci.yml
Fixes #382
We aren't currently starting up the application in the CI. This PR fixes that.
=> test: add smoke-test to CI

lib/lambda_ethereum_consensus/beacon/beacon_chain.ex, lib/lambda_ethereum_consensus/beacon/beacon_node.ex, lib/lambda_ethereum_consensus/beacon/pending_blocks.ex, lib/lambda_ethereum_consensus/beacon/sync_blocks.ex, lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex, lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex, test/unit/pending_blocks_test.exs
Also moved `get_current_status_message` to BeaconChain,
=> chore: rename ForkChoice.Store to ForkChoice.

lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex
Fixes #595
I'm not sure how dialyzer doesn't catch this kind of error...
=> fix: `IncomingRequests.Handler.handle_req` was returning bare strings instead of errors

lib/beacon_api/controllers/v1/beacon_controller.ex, lib/beacon_api/utils.ex, lib/lambda_ethereum_consensus/fork_choice/helpers.ex
A recently merged PR had some errors not caught in code review. We should probably add some tests to catch these kinds of errors.
=> fix: new endpoints were failing some requests

docs/concurrency_design.md
This is a description of the PoC under work: a single process per block for simpler concurrency and independent processing.
Closes #614
=> docs: concurrency proposal - per-block processes

lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
That is supposed to match an empty mapset but it actually matches any mapset.
=> fix: fix faulty MapSet pattern matching.

bench/block_processing.exs, lib/lambda_ethereum_consensus/application.ex, lib/lambda_ethereum_consensus/beacon/beacon_node.ex, lib/lambda_ethereum_consensus/fork_choice/helpers.ex, lib/lambda_ethereum_consensus/p2p/incoming_requests/incoming_requests.ex, lib/lambda_ethereum_consensus/store/blocks.ex, lib/types/store.ex
=> feat: add blocks cache

.gitignore, config/config.exs, metrics/docker-compose.yml, metrics/grafana/provisioning/datasources/loki_ds.yml, metrics/loki/loki.yml, metrics/promtail/promtail.yml
Closes #633
This PR adds Loki and Promtail containers to our docker-compose file. It also removes the login page on Grafana.
=> feat: add loki to docker-compose

config/config.exs, metrics/grafana/provisioning/dashboards/home.json, metrics/promtail/promtail.yml, mix.exs, mix.lock
Closes #641
This PR modifies the format of logs and adds a visualization with the newest log entries in Grafana.
=> feat: label each log message and show in grafana

lib/chain_spec/configs/gen_config.ex, lib/chain_spec/configs/mainnet.ex, lib/chain_spec/configs/minimal.ex, lib/chain_spec/configs/sepolia.ex, lib/chain_spec/presets/gen_preset.ex, lib/chain_spec/presets/mainnet.ex, lib/chain_spec/presets/minimal.ex
Depends on #642
This PR removes duplicate code in configs and presets.
=> refactor: use templates for configs and presets

lib/lambda_ethereum_consensus/state_transition/state_transition.ex
This will give us a broad view of the time it takes to process a block. Example:
```
14:15:02.604 [debug] [Slot processing] took 19 ms
14:15:02.622 [debug] [Slot processing] took 18 ms
14:15:02.678 [debug] [Block processing] took 53 ms
```
=> feat: add debug logs with block processing time

bench/block_processing.exs, lib/beacon_api/controllers/v1/beacon_controller.ex, lib/beacon_api/controllers/v2/beacon_controller.ex, lib/lambda_ethereum_consensus/beacon/beacon_node.ex, lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex, lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/fork_choice/helpers.ex, lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex, lib/lambda_ethereum_consensus/store/blocks.ex, lib/spec/runners/fork_choice.ex, lib/types/store.ex, test/integration/fork_choice/handlers_test.exs
Depends on #682
This PR drops support for storing blocks and states in memory.
=> refactor: remove blocks and states from store

lib/lambda_ethereum_consensus/application.ex, lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/fork_choice/helpers.ex, lib/lambda_ethereum_consensus/store/block_states.ex, lib/lambda_ethereum_consensus/store/blocks.ex, lib/lambda_ethereum_consensus/store/lru_cache.ex, lib/mix/tasks/generate_spec_tests.ex, lib/types/store.ex
=> perf: add states cache

lib/lambda_ethereum_consensus/logger/console_logger.ex
https://github.com/lambdaclass/lambda_ethereum_consensus/pull/703#issuecomment-1932081987
=> fix: "invalid ANSI sequence specification" error

config/runtime.exs, lib/lambda_ethereum_consensus/store/db.ex, test/spec/tasks/generate_spec_tests.ex
=> feat: use different DB locations according to network

bench/block_processing.exs, bench/multiple_blocks_processing.exs, lib/beacon_api/controllers/v1/beacon_controller.ex, lib/beacon_api/controllers/v2/beacon_controller.ex, lib/lambda_ethereum_consensus/fork_choice/helpers.ex, lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex, lib/lambda_ethereum_consensus/store/block_states.ex, lib/lambda_ethereum_consensus/store/block_store.ex, lib/lambda_ethereum_consensus/store/blocks.ex, lib/lambda_ethereum_consensus/store/state_store.ex, test/integration/fork_choice/handlers_test.exs, test/unit/beacon_api_test.exs
=> chore: replace `BlockStore` and `StateStore` with `BlockDb` and `StateDb`

lib/lambda_ethereum_consensus/state_transition/operations.ex
This PR improves the error messages when processing voluntary exits
=> chore: improve voluntary exit errors

lib/lambda_ethereum_consensus/p2p/gossip/gossipsub.ex, lib/lambda_ethereum_consensus/p2p/gossip/handler.ex, lib/lambda_ethereum_consensus/store/blob_db.ex, lib/types/beacon_chain/execution_payload_deneb.ex, lib/types/beacon_chain/execution_payload_header.ex, lib/types/beacon_chain/execution_payload_header_deneb.ex
Closes #753
Depends on #779
This PR adds logic related to subscribing to the blob topics and storing blobs in the DB.
=> feat: subscribe to blob subnets

lib/lambda_ethereum_consensus/beacon/sync_blocks.ex, lib/lambda_ethereum_consensus/p2p/blob_downloader.ex, lib/lambda_ethereum_consensus/p2p/block_downloader.ex, lib/lambda_ethereum_consensus/p2p/req_resp.ex, lib/types/p2p/blob_sidecars_by_root_request.ex, test/unit/req_resp_test.exs
Closes #754
Closes #755
Depends on #790
This PR adds functions for downloading blobs via Req/Resp.
=> feat: add `BlobDownloader`

lib/bls.ex, lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex, lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex, lib/lambda_ethereum_consensus/validator/utils.ex, lib/lambda_ethereum_consensus/validator/validator.ex, lib/utils/bit_list.ex
=> feat: produce attestations

test/spec/runners/finality.ex, test/spec/runners/light_client.ex, test/spec/runners/random.ex, test/spec/runners/sync.ex, test/spec/tasks/generate_spec_tests.ex
Enable Deneb spec tests generation
=> chore: generate deneb spec tests.

lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, test/spec/runners/epoch_processing.ex, test/spec/runners/fork_choice.ex, test/spec/runners/helpers/process_blocks.ex, test/spec/runners/sanity.ex
=> feat: bound the validator activation churn limit

lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, test/spec/runners/operations.ex
**Motivation**
Deneb compatibility
Closes #757
=> feat: increase max attestation inclusion slot for `process_attestation`

lib/lambda_ethereum_consensus/state_transition/operations.ex, test/spec/runners/operations.ex
**Motivation**
Make it compatible with Deneb
Update process_voluntary_exit according to EIP-7044
Closes #759
=> feat: update `process_voluntary_exit` to make it deneb compatible

.fork_version, lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/hard_fork_alias_injection.ex, lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, lib/types/beacon_chain/beacon_block_body_deneb.ex, test/fixtures/block.ex
Since the transition to deneb was completed, our CI fails in the "Start and stop the node" job. This PR fixes this by moving on to deneb as the default fork.
=> feat: set `.fork_version` to "deneb"

docs/specs/beacon-chain.md, docs/specs/fork-choice.md, docs/specs/fork.md, docs/specs/p2p-interface.md, docs/specs/validator.md
=> docs: update consolidated specs with Deneb changes

lib/constants.ex, lib/lambda_ethereum_consensus/state_transition/misc.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, lib/lambda_ethereum_consensus/validator/utils.ex, lib/lambda_ethereum_consensus/validator/validator.ex
=> feat: compute aggregator duties

.github/workflows/ci.yml
https://github.com/lambdaclass/lambda_ethereum_consensus/actions/runs/8348756083/job/22851414715?pr=890#step:5:16
=> ci: update spectest vectors cache path

lib/container.ex, lib/ssz_ex.ex
This PR is the continuation of #823
Closes #815
=> feat: document `SszEx.schema`

.github/workflows/ci.yml, lib/types/beacon_chain/eth1_block.ex, test/spec/runners/ssz_static.ex
=> feat: add `Eth1block` container

.github/workflows/ci.yml, .tool-versions
=> chore: bump Elixir version

config/config.exs, config/runtime.exs
=> feat: add release metadata to sentry

lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex, lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/validator/validator.ex, native/libp2p_port/internal/subscriptions/subscriptions.go, test/unit/libp2p_port_test.exs
=> feat: validator proposal duties lookahead

lib/lambda_ethereum_consensus/p2p/gossip/gossipsub.ex, lib/lambda_ethereum_consensus/p2p/gossip/handler.ex, lib/lambda_ethereum_consensus/p2p/gossip/operations_collector.ex
=> feat: collect slashings and voluntary exits

lib/lambda_ethereum_consensus/p2p/gossip/handler.ex, lib/lambda_ethereum_consensus/p2p/gossip/operations_collector.ex
=> feat: collect attestations

lib/lambda_ethereum_consensus/validator/block_request.ex, lib/lambda_ethereum_consensus/validator/proposer.ex, lib/lambda_ethereum_consensus/validator/validator.ex, test/unit/validator/proposer_test.exs
Related to #911
Also completes `BlockRequest` typespecs, and changes graffiti to `"Lambda: good, nice, gentle"`
=> feat: compute `parent_root` and trivial `eth1_data`

lib/lambda_ethereum_consensus/execution/engine_api.ex, lib/lambda_ethereum_consensus/execution/engine_api/api.ex, lib/lambda_ethereum_consensus/execution/engine_api/mocked.ex, lib/lambda_ethereum_consensus/execution/execution_client.ex, test/unit/execution_test.exs
=> feat: fetch block metadata from Execution Engine

lib/lambda_ethereum_consensus/execution/engine_api.ex, lib/lambda_ethereum_consensus/execution/engine_api/api.ex, lib/lambda_ethereum_consensus/execution/engine_api/behaviour.ex, lib/lambda_ethereum_consensus/execution/engine_api/mocked.ex, lib/lambda_ethereum_consensus/execution/execution_client.ex, lib/lambda_ethereum_consensus/execution/rpc.ex, lib/lambda_ethereum_consensus/validator/validator.ex, test/spec/runners/sync.ex
**Motivation**
Being able to build an execution block
Naive implementation of calling the execution layer to get an execution payload
=> feat: add logic to build an execution payload when proposing blocks.

.recode.exs, bench/block_processing.exs, bench/multiple_blocks_processing.exs, lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex, lib/lambda_ethereum_consensus/fork_choice/handlers.ex, lib/lambda_ethereum_consensus/fork_choice/helpers.ex, lib/lambda_ethereum_consensus/p2p/blob_downloader.ex, lib/lambda_ethereum_consensus/p2p/block_downloader.ex, lib/lambda_ethereum_consensus/state_transition/accessors.ex, lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex, lib/lambda_ethereum_consensus/state_transition/misc.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, lib/lambda_ethereum_consensus/state_transition/predicates.ex, lib/lambda_ethereum_consensus/state_transition/state_transition.ex, lib/libp2p_port.ex, test/unit/ssz_ex_test.exs
Added `AliasExpansion`,  `FilterCount`, `PipeFunOne `.
`TestFileExt` doesn't seem to be working.
=> chore: add more recode rules.

lib/lambda_ethereum_consensus/execution/execution_chain.ex, lib/lambda_ethereum_consensus/validator/block_builder.ex, lib/lambda_ethereum_consensus/validator/validator.ex, lib/types/deposit_tree.ex, test/unit/deposit_tree_test.exs
=> feat: add deposits to proposed blocks

lib/lambda_ethereum_consensus/execution/execution_client.ex, lib/lambda_ethereum_consensus/state_transition/operations.ex, lib/lambda_ethereum_consensus/validator/block_builder.ex
=> feat: add withdrawals when building block

lib/lambda_ethereum_consensus/validator/block_builder.ex, test/unit/validator/block_builder_test.exs
From the validator specs:
```
Note: In this section, state is the state of the slot for the block proposal without the block yet applied. That is, state is the previous_state processed through any empty slots up to the assigned slot using process_slots(previous_state, slot).
```
We call that state `mid_state` here
=> fix: use intermediate state when building a block.

lib/lambda_ethereum_consensus/beacon/beacon_chain.ex, lib/lambda_ethereum_consensus/validator/validator.ex
This PR refactors the `Validator` module to update its state on every slot, even if it's empty.
=> refactor: update state when possible

lib/lambda_ethereum_consensus/validator/block_builder.ex, lib/ssz_ex/merkleization.ex, test/unit/validator/block_builder_test.exs
This PR implements the computation of the commitment inclusion proofs for the blob sidecars
=> feat: compute blob commitment inclusion proofs

lib/lambda_ethereum_consensus/execution/engine_api/mocked.ex
This results in a lot of unneeded restarts on our server.
=> fix: return error instead of raising on mock

lib/beacon_api/helpers.ex, lib/lambda_ethereum_consensus/beacon/beacon_chain.ex, test/unit/beacon_api/beacon_api_v1_test.exs
=> fix: remove the :ok tuple when calling get_current_status_message

lib/lambda_ethereum_consensus/beacon/store_setup.ex
**Motivation**
The application was crashing but I wasn't seen any log before. This fixes it
=> fix: make sure to flush the logger before halting.

lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex, lib/lambda_ethereum_consensus/store/block_db.ex, lib/lambda_ethereum_consensus/store/state_db.ex
This PR adds blocks pruning. Blocks older than the last finalized one are removed.
Closes #1091
=> feat: add blocks pruning

lib/lambda_ethereum_consensus/store/kv_schema.ex, test/unit/store/kv_schema_test.exs
Adds to kv schema:
- stream_all_keys
- stream_keys
- all
- first
Closes #1220
=> feat: add first, all, stream_keys and stream_all_keys functions to KvSchema

assertoor-config.yml
**Motivation**
Nethermind was breaking the load of assertoor
=> fix: make assertoor config work again

.github/SECURITY.md, README.md
**Motivation**
Improve visibility of the project's security reporting process.
Add Security Reporting Instructions to README.md and SECURITY.md
=> chore: add Security Reporting Instructions
