lambdaclass/lambda_ethereum_consensus

- .formatter.exs
- .gitignore
- Makefile
- README.md
- lib/lambda_ethereum_consensus.ex
- lib/lambda_ethereum_consensus/application.ex
- mix.exs
- test/lambda_ethereum_consensus_test.exs
- test/test_helper.exs
Basic setup for the project with:
- `make` targets for deps, terminal run and test. 
- Basic mix project with a supervisor.
Closes #7
> feat: mix project setup

- .github/workflows/ci.yml
- .gitignore
- Makefile
- lib/lambda_ethereum_consensus.ex
- mix.exs
- mix.lock
Added basic CI with Dialyzer.
Closes #10
> build: add basic CI and dialyzer

- docs/consensus.md
- docs/finality.md
- docs/fork_choice.md
This PR adds some notes for the basic theory of fork-choice in ethereum
Closes #13
> docs: add consensus basic notes

- .github/workflows/ci.yml
Adds Rust caches to corresponding jobs, cleans up some unneeded env vars passed to actions, and pins the ubuntu version to latest.
> ci: add Rust caches

- README.md
**Motivation**
This pull request addresses issue #38 
Added instructions for installing Go, Erlang and Elixir directly from official mirrors and through the asdf tool version manager.
Closes #38
> docs(readme): add instructions for dependencies

- .github/workflows/ci.yml
- Makefile
- native/ssz_nif/src/types/beacon_chain.rs
Closes #93
This PR adds a target that formats the project's code and CI checks to enforce its usage.
> chore: add `make fmt` target

- native/ssz_nif/src/utils/from_elx.rs
- native/ssz_nif/src/utils/helpers.rs
- native/ssz_nif/src/utils/mod.rs
Closes #101
This PR makes the `FromElx` trait return a `Result<Self, FromElxError>`. The `FromElxError` simply wraps a `String`, but should make it easier to refactor gradually in the future.
> feat: add error handling to `FromElx` trait

- .github/workflows/ci.yml
**Motivation**
We don't want to waste resources and time by running the CI when only .md files change
> build: ignore running ci when changing only markdown files.

- lib/ssz.ex
- lib/ssz_types/execution_payload.ex
- lib/ssz_types/execution_payload_header.ex
- test/spec/utils/generator.ex
**Motivation**
We want the custom rules to be as closer to the type definition so that we don't bloat the Ssz module. Addionally, if we have a type A with special encoding/decoding rules that is contained inside type B, we shouldn't have to define the rule for type B, it should work out of the box
> refactor: move special encoding/decoding rules to the types themselves.

- lib/ssz.ex
Closes #217
From the `Kernel.function_exported?` documentation:
> Returns true if module **is loaded** and contains a public function with the given arity, otherwise false.
Since the module wasn't loaded at first, we weren't encoding U256s properly.
> fix: ensure module is loaded before encoding/decoding

- .tool-versions
The latest macOS release has problems with Elixir when using OTP 25. This PR bumps the version used in `.tool-versions` to OTP 26, which doesn't have these problems.
Also flips the order of Elixir and Erlang versions listed, since:
> Even though it's possible to install Elixir first, it's recommended to install Erlang first.
> chore: bump OTP version to 26

- lib/lambda_ethereum_consensus/p2p/block_downloader.ex
- lib/lambda_ethereum_consensus/store/block_store.ex
- lib/lambda_ethereum_consensus/store/db.ex
- lib/lambda_ethereum_consensus/store/utils.ex
Depends on #211 #225
This PR adds missing block detection to our DB, and uses that to request blocks from peers. It also refactors the module to only serve the DB handle and allowing concurrent access to it, since _levelDB_ is already thread-safe.
> feat: request missing blocks only

- lib/lambda_ethereum_consensus/store/block_store.ex
The error happened when running the node without checkpoint sync. The match fails because an `if` without `else` returns `nil` when the condition is `false`, but in that case, we'd like it to silently pass.
> fix: error "no with clause matching: nil"

- lib/lambda_ethereum_consensus/application.ex
- lib/lambda_ethereum_consensus/fork_choice/tree.ex
- test/unit/tree.exs
This PR introduces a GenServer module that:
- Allows blocks to be added to a tree structure.
- The weights of the branch are recalculated when adding a block.
- The head is found when adding a block and cached for future requests.
Out of the scope of this PR:
- Representing slots so that one can request the block for a certain slot.
Closes #270
> feat: fork Tree PoC

- test/spec/runners/epoch_processing.ex
- test/spec/runners/operations.ex
- test/spec/utils/compile_time.ex
- test/spec/utils/generator.ex
- test/spec/utils/testcase.ex
- test/spec/utils/utils.ex
This PR renames `read_ssz_from_file` to `read_ssz_from_optional_file!`, to better convey its intended usage. It also changes it to return the value or `nil`, instead of wrapping it in an `:ok` tuple.
Along with that, it also enables `epoch_processing` spec-tests and changes the `handle_case` functions to _private_ visibility (so that non-usage gives a warning).
Finally, it splits the utils module into compile-time and runtime utilities, and caches some used values to reduce the amount of recompiling needed.
> refactor: clean up spec tests a bit

- .tool-versions
Compiling the libp2p port or NIF results in this message:
```
ld: warning: '/private/var/folders/9k/wxsp3xfd6p9_9sbctbjcp1w80000gn/T/go-link-550978199/go.o' has malformed LC_DYSYMTAB, expected 119 undefined symbols to start at index 36231, found 142 undefined symbols starting at index 95
```
Looking for a solution, I found golang/go#61229. It seems this issue was fixed in later versions of the Go toolchain, and bumping it fixes it.
> fix: ld warning, malformed LC_DYSYMTAB

- test/spec/mainnet.ex
- test/spec/runners/epoch_processing.ex
- test/spec/runners/operations.ex
- test/spec/runners/ssz_static.ex
This PR enables generation of non-capella mainnet spec-tests. That way, we can run them on cases like #313 that have vectors only on phase0.
> chore: generate all mainnet test cases

- lib/lambda_ethereum_consensus/application.ex
- lib/lambda_ethereum_consensus/fork_choice/store.ex
- lib/lambda_ethereum_consensus/fork_choice/supervisor.ex
This PR makes checkpoint sync optional after doing it once. After that, we fetch the initial state and block from the DB. With this change, the node's startup time is reduced considerably.
> feat: make checkpoint sync optional again

- Makefile
This makes it so you don't need to explicitly run `make proto`: `make` takes care of it for you.
> chore: add `.proto` file dependency to `proto` make target

- lib/utils/config.ex
This adds a preprocessing step that enquotes YAML entries starting with '0x', and a post-processing step that parses those strings into raw bytes.
> fix: patch read config file

- lib/beacon_api/controllers/v1/beacon_controller.ex
- lib/lambda_ethereum_consensus/fork_choice/store.ex
- lib/lambda_ethereum_consensus/fork_choice/supervisor.ex
- lib/lambda_ethereum_consensus/store/block_store.ex
**Motivation**
We need to store signed blocks since we will need to pass them to other peers on request.
> fix: store signed blocks instead of regular blocks.

- lib/spec/runners/epoch_processing.ex
This PR removes duplicated code in `epoch_processing` handlers, and changes assertions to use the new `Diff.diff/2` function
> refactor: simplify "epoch_processing" handlers

- lib/lambda_ethereum_consensus/application.ex
- lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex
- lib/lambda_ethereum_consensus/p2p/incoming_requests/incoming_requests.ex
- lib/lambda_ethereum_consensus/p2p/incoming_requests/receiver.ex
- lib/lambda_ethereum_consensus/p2p/incoming_requests/supervisor.ex
Closes #344
This PR:
- splits `IncomingRequestHandler` into `IncomingRequests.Handler` and `IncomingRequests.Receiver`, with a supervisor named `IncomingRequests`
- `IncomingRequests` starts both a `Task.Supervisor` with name `IncomingRequests.Handler`, and a `GenServer` `IncomingRequests.Receiver` that receives the requests
- each time `Receiver` gets a request, it starts an async task via the `Task.Supervisor`
> perf: parallelize `IncomingRequestHandler`

- .formatter.exs
**Motivation**
In VsCode, this line is making the formatting task extremely slow (10+ seconds). Not sure what the reason is but removing it fixes the issue. Also, I don't know what the purpose of this line is.
> build: fix formatter taking forever.

- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
- lib/lambda_ethereum_consensus/fork_choice/store.ex
- lib/lambda_ethereum_consensus/p2p/gossip_handler.ex
- lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex
- lib/lambda_ethereum_consensus/state_transition/state_transition.ex
- lib/ssz_types/store.ex
- test/fixtures/block.ex
- test/unit/pending_blocks_test.exs
~Depends on #381~
Closes #377
This PR implements the `on_block` handler and calls it from `ForkChoice.Store`. To do this, I had to change the `BeaconBlock`s stored in `PendingBlocks` to `SignedBeaconBlock`s.
NOTE: the implementations of `state_transition` and `process_justification_and_finalization` are missing and are left for later PRs.
> feat: add `on_block` handler

- lib/lambda_ethereum_consensus/application.ex
- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- lib/lambda_ethereum_consensus/beacon/sync_blocks.ex
- lib/lambda_ethereum_consensus/fork_choice/store.ex
- lib/lambda_ethereum_consensus/p2p/block_downloader.ex
**Motivation**
When syncing from checkpoint, we are a couple of hundred blocks behind. Instead of relying on Pending Blocks to download parents one by one, let's optimistically download blocks from the checkpoint sync slot.
Added `SyncBlocks` module a task that is triggered on application start that downloads all blocks from the last checkpoint sync to the current slot.
> feat: add optimistic block sync from checkpoint.

- lib/lambda_ethereum_consensus/fork_choice/checkpoint_sync.ex
- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
- lib/lambda_ethereum_consensus/fork_choice/supervisor.ex
- lib/lambda_ethereum_consensus/state_transition/state_transition.ex
- lib/lambda_ethereum_consensus/utils.ex
Depends on #392
This PR [moves the checkpoint-sync functions to a new module](https://github.com/lambdaclass/lambda_ethereum_consensus/commit/d0af2b70ac27689ff19cfbdb0dcf211b5ee966ac) and [moves some functions used in state processing into the `Utils` module](https://github.com/lambdaclass/lambda_ethereum_consensus/commit/c5a59816cf3f85868e4b014cab0d9ac77f229a8c).
> refactor: move some functions to utils

- lib/lambda_ethereum_consensus/beacon/sync_blocks.ex
We currently have a bottleneck on `Libp2pPort`. This PR reduces the amount of concurrent requests used when syncing, to avoid hogging the limited network resources.
> fix: reduce `SyncBlocks` max concurrency

- lib/lambda_ethereum_consensus/beacon/sync_blocks.ex
- lib/lambda_ethereum_consensus/fork_choice/store.ex
This PR fixes the "Remaining blocks: ..." message by counting the number of blocks remaining instead of approximating it. It also lowers the log level of attestation notifications to debug, since it's too spammy.
> fix: number of remaining blocks is rounded up

- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- lib/lambda_ethereum_consensus/beacon/sync_blocks.ex
- lib/lambda_ethereum_consensus/fork_choice/store.ex
- lib/lambda_ethereum_consensus/p2p/gossip_handler.ex
- lib/lambda_ethereum_consensus/state_transition/state_transition.ex
**Motivation**
We're seeing that when there is a big load of messages to the `ForkChoice.Store` GenServer (typically a combination of ~500 attestations and ~100 blocks that are being synced) then some other call to the same server (for example, to get the current slot) ends up in 5000ms timeout.
We need to think about how to we deal with this holistically. But in the meantime, I added a couple of hacks to ease the load.
Some questions:
- Do we really need to process 500 aggregated attestations per slot? (In one example for a single slot it meant 141416 attestations. That numbers times 32 is 4M, much more than the 0.8M of active validators on mainnet, if my math is right). 
- Should we create different GenServers to process attestations for example?
> perf: ease the load to the fork choice GenServer.

- .formatter.exs
- .gitignore
- Makefile
- mix.exs
This PR fixes the issue with `make lint` taking forever to run. This was because the formatter included generated test files. The solution was doing a partial expansion of the test folder, and excluding the `test/generated` folder from the matched paths.
Also, I moved the protobuf generated files to the `proto` directory, so the formatter and linter don't include them.
> fix: eternal `make lint` runs

- lib/lambda_ethereum_consensus/p2p/block_downloader.ex
**Motivation**
Before, if you were requesting several blocks and there was one failure, all the request would be considered failed. Instead of that, just return the blocks that have been succesfull
> fix: allow some block downloads to fail

- .github/workflows/ci.yml
**Motivation**
Let's prevent warnings to slip into main
Also, `dialyzer` was performing the compilation anyway so this shouldn't take more time (also, it's better to have them separated for better debugging)
> build: warnings on Elixir compilation should not pass the CI.

- lib/lambda_ethereum_consensus/state_transition/operations.ex
- lib/spec/runners/operations.ex
Hash tree root calculation has been fixed on https://github.com/lambdaclass/lambda_ethereum_consensus/pull/469, lets adapt the `process_execution_payload` function to use it.
> fix: `process_execution_payload` hash tree root calculation

- lib/lambda_ethereum_consensus/state_transition/accessors.ex
- lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex
- lib/lambda_ethereum_consensus/state_transition/misc.ex
- lib/lambda_ethereum_consensus/state_transition/state_transition.ex
- lib/ssz_types/beacon_chain/beacon_state.ex
This PR optimizes the `process_rewards_and_penalties` function so that it takes an acceptable amount of time to run. It also inverts the check in `maybe_process_epoch` so that `process_epoch` only runs on an epoch start, instead of on every slot that's not the start of an epoch.
> perf: optimize `process_rewards_and_penalties` (+fix)

- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
- lib/lambda_ethereum_consensus/state_transition/accessors.ex
- lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex
- lib/spec/runners/fork_choice.ex
- lib/spec/runners/sanity.ex
We were pre-calculating block hashes with `Accessors.get_block_root` while also propagating any errors from those calls. This was a problem since those calls are done inline in the spec, and inside an `if`. If that branch wasn't taken, then our implementation would fail, differing from the spec's behavior.
> fix: don't pre-calculate hashes in `weigh_justification_and_finalization`

- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
- lib/lambda_ethereum_consensus/fork_choice/helpers.ex
- lib/spec/runners/fork_choice.ex
Closes #449
This PR squashes two bugs:
- we weren't breaking ties correctly in `get_head` (5c909fcf8f2601220e25bf9ee341bf318d60652b)
- we had an inverted condition in `update_latest_messages` (32905327e42c0dff02a36e6ea809309d0430a390)
With this, all spec-tests for fork-choice run correctly 🥳
> fix: wrong head resolving in fork-choice spec-tests

- lib/constants.ex
- lib/lambda_ethereum_consensus/state_transition/accessors.ex
- lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex
- lib/lambda_ethereum_consensus/state_transition/misc.ex
- lib/lambda_ethereum_consensus/state_transition/operations.ex
- lib/spec/runners/random.ex
- lib/spec/runners/sync.ex
- lib/ssz_types/mod.ex
This fixes two different bugs:
- we were overwriting `i` with the value of `compute_shuffled_index` (be1f9ca13418cb0756080dc3303217e10534b265)
- we were using `uint_to_bytes4` instead of `uint_to_bytes8` (709dc942f6932d13cf85e965fdf6d3e7f1fe0853)
Also some refactors: be1f9ca13418cb0756080dc3303217e10534b265...f20b58080795a2c1c9bf088f0fa8953494a1c6d6
This makes all tests in the `random` runner pass 🚀
> fix: errors in `compute_proposer_index`

- lib/lambda_ethereum_consensus/state_transition/misc.ex
This reduces the time of `process_attestation` by ~0.5s (~30%)
> perf: optimize `Misc.compute_committee` a bit

- lib/lambda_ethereum_consensus/state_transition/accessors.ex
- lib/lambda_ethereum_consensus/state_transition/operations.ex
This reduces the time spent in each `process_attestation` to 0.7s (down from ~1.3s, so ~45% decrease)
> perf: reduce `get_beacon_committee` calls

- README.md
- lib/lambda_ethereum_consensus/fork_choice/store.ex
When I ran `make iex`, I got the error below:
```bash
14:41:45.843 [error] GenServer LambdaEthereumConsensus.ForkChoice.Store terminating
** (stop) bad return value: {:reply, {:ok, %SszTypes.StatusMessage{fork_digest: <<187, 164, 218, 150>>, finalized_root: <<238, 54, 2, 127, 35, 225, 4, 13, 165, 18, 215, 171, 29, 86, 84, 169, 94, 202, 243, 112, 26, 144, 8, 70, 232, 19, 235, 127, 37, 224, 135, 54>>, finalized_epoch: 241263, head_root: <<156, 160, 140, 200, 88, 234, 118, 115, 68, 6, 5, 16, 244, 87, 86, 48, 100, 15, 96, 248, 121, 156, 85, 118, 59, 226, 65, 230, 130, 34, 161, 1>>, head_slot: 7720480}}}
Last message (from #PID<0.827.0>): :get_current_status_message
14:41:45.854 [error] Task #PID<0.827.0> started from #PID<0.440.0> terminating
** (stop) exited in: …
```
> fix: status message handler

- lib/lambda_ethereum_consensus/cli.ex
The name of the cli option was different than the log when the option was not provided (execution_jwt vs execution-jwt)
> fix: rename cli options related to execution client.

- lib/lambda_ethereum_consensus/cli.ex
Currently, the Engine API isn't integrated into the rest of the node. This PR removes the `System.exit` call when `--execution-jwt` isn't specified. This is intended as a quick patch, and should ideally be solved in another way, like disabling the whole Engine API module when either the endpoint or JWT flags are unspecified (or when some special flag IS specified).
> fix: allow not passing `--execution-jwt` flag

- config/config.exs
- config/runtime.exs
- lib/lambda_ethereum_consensus/application.ex
**Motivation**
Config should ideally be set in the config files. Before this change, we were changing config values in application.
- The only bad part is that we're no longer logging when there are config values that are not valid.
> refactor: move config to runtime.exs.

- lib/lambda_ethereum_consensus/fork_choice/supervisor.ex
- lib/lambda_ethereum_consensus/state_transition/accessors.ex
- lib/lambda_ethereum_consensus/state_transition/cache.ex
- lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex
- lib/lambda_ethereum_consensus/state_transition/mutators.ex
- lib/lambda_ethereum_consensus/state_transition/operations.ex
- lib/mix/tasks/generate_spec_tests.ex
- lib/spec/runners/rewards.ex
- lib/spec/runners/ssz_static.ex
- lib/spec/utils.ex
- lib/types/beacon_chain/beacon_state.ex
- lib/utils/diff.ex
- mix.exs
This reduces whole block processing time to ~10.5s
> perf: store `X_epoch_participation` and `balances` in vectors

- lib/lambda_ethereum_consensus/state_transition/accessors.ex
- lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex
- lib/lambda_ethereum_consensus/state_transition/mutators.ex
- lib/lambda_ethereum_consensus/state_transition/operations.ex
- lib/lambda_ethereum_consensus/state_transition/predicates.ex
This shaves ~0.6s off the block processing time. Briefly, it just replaces calls to `get_unslashed_participating_indices` and to `get_total_balance` with calls to a new function that merges both functions.
> perf: optimize `process_justification_and_finalization`

- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
- lib/lambda_ethereum_consensus/fork_choice/helpers.ex
- lib/lambda_ethereum_consensus/fork_choice/store.ex
Fixes #564
We commented this out because it was too slow. This PR uncomments it and bypasses some attestation checks (for now).
Changelog:
* uncomments processing of attestations and attester-slashings included in blocks
* bypasses attestation processing for unknown-block attestations (as it was too difficult to fix right now) #573
* hardcodes the status message answer (`Helpers.get_head` is too slow, and uncached) #572
* increases `ForkChoice.Store`'s timeout
> fix: process block attestations and slashings

- Makefile
When running `make clean`, following runs could fail to load rustler-compiled artifacts. I guess this is because we are removing these on `make clean`, but didn't remove the NIF modules so they weren't recompiled.
> fix: run `mix clean` on `clean` target

- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/beacon/checkpoint_sync.ex
Fixes #565
New workflow:
1. fetch both state and block optimistically
2. if slots mismatch, we just ask for the block on the state's slot
We might want to ask for the state if the block has a higher slot, but I leave that for future PRs (but it's not a priority).
> fix: fetch block when checkpoint sync's race condition happens

- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/p2p/gossip/consumer.ex
- lib/lambda_ethereum_consensus/p2p/gossip/gossipsub.ex
- lib/lambda_ethereum_consensus/p2p/gossip/handler.ex
**Motivation**
We want to support more networks than mainnet
Gets the fork digest from the anchor state. Uses the fork digest to subscribe to the corresponding topic
> fix: calculate fork context when subscribing to topics

- Makefile
- metrics/docker-compose.yml
Running the container in Linux with `docker compose` was resulting in errors due to `host.docker.internal` not being configured.
> fix: declare `host.docker.internal` in docker compose schema

- lib/lambda_ethereum_consensus/telemetry.ex
- metrics/grafana/provisioning/dashboards/home.json
We are having trouble with overflowing message queues. This metric might be useful for easy debugging of these kind of issues.
> feat: add message queues aggregated lengths metric

- test/unit/pending_blocks_test.exs
Sometimes this test would fail because some other test put the `MinimalConfig` in the config.
Here's an example: https://github.com/lambdaclass/lambda_ethereum_consensus/actions/runs/7488525574/job/20383206386
> fix: set used config before running test

- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
Although a really rare case, when fetching the latest state without a block for the same slot, the node would raise a match error instead of cleanly exiting.
> fix: avoid hard match in `BeaconNode.init`

- lib/lambda_ethereum_consensus/p2p/metadata.ex
Two bugs:
- 7b746f0ebc8943c75e3353fd4642b36429028532: `GenServer.handle_call` not returning state
- 85e3e161d8354c2eaeb93f78a0078206e31447e5: some setters (unused, so no problem) used `GenServer.call` instead of `GenServer.cast`, while the handlers used `handle_call`
> fix: metadata genserver not returning state

- lib/ssz.ex
> fix: use pattern-matching instead of `String` when encoding `u256`s

- lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex
- lib/lambda_ethereum_consensus/telemetry.ex
- metrics/grafana/provisioning/dashboards/home.json
This PR adds a new metric, namely the time it takes to process a new block. It also adds a heatmap visualization. Note this has hardcoded bucket values, that need to be changed at the node level. We may need to change this in the future, but it should be as simple as changing the metric type.
New vis:
> feat: add block processing time metric

- config/networks/sepolia/config.yaml
Some configuration data was missing, so I copied them from the mainnet one since they are similar (didn't double-check, but they should be the same, cc @mpaulucci ).
> fix: add missing networking configuration for Sepolia network

- lib/chain_spec/configs/mainnet.ex
- lib/chain_spec/configs/minimal.ex
- lib/chain_spec/configs/sepolia.ex
- lib/chain_spec/presets/mainnet.ex
- lib/chain_spec/presets/minimal.ex
When changing the YAML files, the configs aren't automatically recompiled. This PR fixes that.
> fix: recompile configs and presets on file change

- lib/lambda_ethereum_consensus/execution/execution_client.ex
- lib/lambda_ethereum_consensus/state_transition/operations.ex
- lib/spec/runners/operations.ex
**Motivation**
Eventually we will need to store if the block was optimistic or not, so we need to pass that back to the state transition function
> refactor: improve return values from execution client.

- lib/lambda_ethereum_consensus/store/blocks.ex
This caused the cache to grow without bounds
> fix: wasn't linking data to time data in LRU cache

- .github/workflows/ci.yml
- test/integration/fork_choice/handlers_test.exs
We had some stale code that was throwing warnings with CI passing. This PR fixes those warnings and adds a flag in CI to catch these.
> fix: warnings in CI tests

- lib/lambda_ethereum_consensus/beacon/beacon_chain.ex
- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- lib/lambda_ethereum_consensus/beacon/sync_blocks.ex
- lib/lambda_ethereum_consensus/fork_choice/simple_tree.ex
- lib/lambda_ethereum_consensus/p2p/block_downloader.ex
- lib/lambda_ethereum_consensus/state_transition/misc.ex
This PR fixes a race condition we had. If during start-up we received the anchor block's parent, we marked that one as pending, and thus also marked our current anchor block as pending, causing all block processing to stop.
> fix: don't download blocks older than anchor slot in SyncBlocks

- config/runtime.exs
- lib/lambda_ethereum_consensus/application.ex
Closes #684
This PR introduces a new flag `--mode`, which sets the application mode. "db" starts the application with DB-related modules only, while "full" is the default and starts all features. This is useful for manual debugging and for running tests.
> feat: add "DB-only" mode

- docs/concurrency_design.md
After some feedback:
- Removed the downloader task, it can be a block processor stage too. It removes one more passing around of the block and one more independent thing to take care about.
- The GenServer now exits instead of waiting, and is respawned at a latter stage instead of receiving a message.
- Some typos fixed.
> docs: refine per-block-process design

- .github/dependabot.yml
This PR adds the configuration file for [github's dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates). Merging this with main should enable the feature.
> chore: add dependabot version updates

- bench/ssz.exs
- lib/lambda_ethereum_consensus/state_transition/misc.ex
- lib/ssz_ex.ex
- lib/types/store.ex
Since the function is just an "alias" to `:crypto.hash`, we can safely inline all calls. This gives a ~5% performance increase when hashing, according to benchmarks.
> perf: inline `SszEx.hash` function

- .github/workflows/ci.yml
- Makefile
- README.md
- config/runtime.exs
- lib/lambda_ethereum_consensus/application.ex
- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/beacon/checkpoint_sync.ex
This PR renames `--checkpoint-sync` flag to `--checkpoint-sync-url` flag, in order to prepare for #726. Also, this name is the one used by both Teku and Lighthouse.
> chore: append "-url" to "checkpoint-sync" flag

- bench/shuffling_bench.ex
- lib/lambda_ethereum_consensus/state_transition/shuffling.ex
- test/spec/runners/shuffling.ex
- test/unit/shuffling_test.exs
**Motivation**
Shuffling a whole list should be much more efficient than calling `compute_shuffled_index` on every single item.
Lighthouse implementations claims it can be up to 250x more efficient than computing `compute_shuffled_index` through the entire list, see: https://github.com/sigp/lighthouse/blob/c11638c36c25f3af910eecd33a6e45d1caa99f1f/consensus/swap_or_not_shuffle/src/shuffle_list.rs#L55
In my case I've observed "only" 10x improvements so far:
```
Name                             ips        average  deviation         median         99th %
shuffle_list                  254.79        3.92 ms    ±10.57%        3.90 ms        4.29 ms
compute_shuffled_index         22.14       45.17 ms     ±2.66%       45.24 ms       52.94 ms
Comparison:
shuffle_list …
```
> perf: add `shuffle_list` function

- lib/lambda_ethereum_consensus/execution/execution_client.ex
- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
**Motivation**
I want to avoid confusion, since the two functions exists in the spec, but the one we're implementing is actually `notify_new_payload`.
> chore: rename `verify_and_notify_new_payload` to `notify_new_payload`.

- Makefile
- test/spec/tasks/generate_spec_tests.ex
I was having some problems when changing the version listed in `.spectest_version`. This PR fixes that.
> fix: make spec test generation depend on selected version

- test/spec/tasks/generate_spec_tests.ex
When running `make spec-test` it sometimes clashes with db files, trying to load them as test files, while failing to run. This fixes that by using a different folder for the DBs
> fix: use `tmp/` for test DBs

- docs/architecture.md
- docs/bindings_go.md
- docs/bitvectors.md
- docs/clients.md
- docs/concurrency_design.md
- docs/consensus.md
- docs/finality.md
- docs/fork_choice.md
This PR fixes some typos present in the docs, with the help of an online grammar checker.
> docs: fix typos

- docs/specs/beacon-chain.md
- docs/specs/fork-choice.md
- docs/specs/p2p-interface.md
- docs/specs/validator.md
Closes #769
Updates the consolidated specs from version ~v1.3.0 to [v1.4.0-beta.7](https://github.com/ethereum/consensus-specs/tree/v1.4.0-beta.7).
> docs: update consolidated specs to v1.4.0-beta.7

- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- lib/lambda_ethereum_consensus/store/blocks.ex
This PR:
- avoids checking if a block's parent was processed if we know it's being downloaded
- checks preemptively if a block was already processed when adding the block to `PendingBlocks`
- restricts the `state` type to expected values
- simplifies the code a bit (adding a `has_block?` helper, and removing an `if`)
The first two could potentially solve a message queue overflow we're having with the `Blocks` cache.
> refactor: simplify `PendingBlocks`

- config/runtime.exs
- lib/lambda_ethereum_consensus/telemetry.ex
Closes #813
This PR adds a `--metrics` flag that enables metrics and optionally overrides the default port (e.g. `--metrics 9569`).
> feat: add `--metrics` flag for enabling metrics

- config/runtime.exs
- lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex
- lib/lambda_ethereum_consensus/validator/utils.ex
- lib/lambda_ethereum_consensus/validator/validator.ex
- lib/libp2p_port.ex
This PR fixes six bugs:
- match on old `BeaconBlocksByRoot` struct
- not matching new possible results in `map_block_result`
- use of old enum value `:unsubscribe` in `Lib2pPort`
- validator not handling `StateTransition.process_slots` results
- BLS library not allowing all-balls as secret key
- default logger not logging any metadata
> fix: bugs in Libp2pPort and IncomingRequests.Handler

- .github/workflows/ci.yml
- config/config.exs
- test/spec/tasks/generate_spec_tests.ex
This PR adds the deneb spectests to the CI along with an "All spec-tests passed" job to simplify required checks. Before merging this, we'll need to modify them to un-require the old spectests, and require the new job.
> ci: run the spectests for deneb hard-fork

- .github/workflows/ci.yml
- .github/workflows/ci_skipped.yml
- test/spec/runners/fork_choice.ex
This PR modifies the "All spec-tests passed" job to correctly fail when some of the spec-test jobs fail. It also updates the "CI-skipped" workflow with the new required job
> ci: fix CI required checks

- config/runtime.exs
- lib/lambda_ethereum_consensus/execution/auth.ex
- lib/lambda_ethereum_consensus/execution/engine_api.ex
- lib/lambda_ethereum_consensus/execution/engine_api/api.ex
- lib/lambda_ethereum_consensus/execution/engine_api/mocked.ex
- lib/lambda_ethereum_consensus/execution/execution_client.ex
Closes #756
This PR adds a new RPC call to the Engine API, and integrates it with the existing `ExecutionClient` module. It also simplifies the `Auth` module a bit.
> feat: add `engine_newPayloadV3` to `EngineApi`

- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
Related to #765
This PR adds the blob availability check of the `on_block` handler, but with a stubbed implementation, that should be added in a following PR.
> feat: add blob availability check (stubbed)

- lib/kzg.ex
- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
- lib/lambda_ethereum_consensus/store/blob_db.ex
- lib/types/blobdata.ex
- test/spec/runners/fork_choice.ex
- test/spec/tasks/generate_spec_tests.ex
- test/spec/utils.ex
> feat: check blob data availability

- lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex
- lib/lambda_ethereum_consensus/validator/validator.ex
- lib/utils/bit_field.ex
Depends on #890
Closes #839
Closes #840
This PR adds the logic of `SignedAggregateAndProof` creation and broadcasting. Also: it adds some typespecs that were missing, and filters incoming attestations leaving only those matching our vision.
> feat: construct and publish aggregated attestations

- lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex
- lib/lambda_ethereum_consensus/p2p/gossip/gossipsub.ex
- lib/lambda_ethereum_consensus/p2p/gossip/handler.ex
- lib/lambda_ethereum_consensus/p2p/gossip/operations_collector.ex
> feat: collect `BLSToExecutionChange` from gossip

- lib/ssz_ex.ex
- lib/utils/zero_hashes.ex
This PR simplifies `ZeroHashes.compute_zero_hashes`, moves the `get_zero_hash` logic to `ZeroHashes`, and makes `Ssz.get_zero_hash/1` public.
> refactor: simplify `ZeroHashes`

- lib/lambda_ethereum_consensus/validator/block_request.ex
- lib/lambda_ethereum_consensus/validator/proposer.ex
- lib/lambda_ethereum_consensus/validator/validator.ex
- lib/types/beacon_chain/beacon_block_body.ex
- test/unit/validator/proposer_test.exs
Closes #912
Closes #913
Closes #914
Closes #916
Closes #918
This PR refactors the parameters of `Proposer.construct_block`, and allows passing arbitrary operations to add onto the block. It also updates the `Validator` and tests.
> feat: add operations to block

- lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex
Running the node on the server, we got the warning:
```
warning: negative steps are not supported in String.slice/2, pass 34..-12//1 instead
```
To fix this, we replace `String.slice/2` with `String.trim_trailing/2`.
> fix: replace `slice` with `trim_trailing`

- lib/lambda_ethereum_consensus/validator/validator.ex
This fixes a bug we were having when attesting on empty slots:
```
no match of right hand side value: {:error, "slot is older than state"}
```
Since we process duties each time a block arrives, we don't notice the empty slot and try to attest with the state from the next slot, which triggers the error.
> fix: attesting on empty slots with the wrong state

- lib/ssz_ex.ex
- test/unit/ssz_ex_test.exs
This PR makes SszEx module agnostic of the list implementation being used (removing Aja.Vectors). Only Enumerable protocol is required.
> refactor: take Aja.Vectors out of SszEx module

- lib/lambda_ethereum_consensus/beacon/beacon_chain.ex
- lib/lambda_ethereum_consensus/validator/validator.ex
Closes #926
This PR adds a static pub-sub to `BeaconChain`, that notifies the `Validator` whenever a third of a slot starts. That way we can send attestations, aggregates, and blocks when they _should_ be published, instead of when a new block happens to arrive.
> feat: make `BeaconChain` send ticks to `Validator`

- .formatter.exs
- .recode.exs
Small fix. Also adds `.recode.exs` to autoformatted files.
> chore: ignore `test/generated` files in recode

- lib/ssz_ex/decode.ex
- test/unit/ssz_ex_test.exs
This PR fixes a bug when trying to decode a container and the received binary is shorter than expected.
Will handle error messages on a different PR.
Closes #896
> fix: handle shorter byte lengths than expected

- lib/lambda_ethereum_consensus/p2p/gossip/consumer.ex
Since the error isn't on our side, we shouldn't be so noisy about it.
> chore: reduce log level for gossipsub decode error

- lib/ssz_ex/encode.ex
- lib/ssz_ex/merkleization.ex
- test/unit/ssz_ex_test.exs
This PR normalizes the rest of the error messages in our SSZ module.
Closes https://github.com/lambdaclass/lambda_ethereum_consensus/issues/986
> refactor: normalize SSZ error messages

- lib/ssz_ex/decode.ex
- lib/ssz_ex/encode.ex
- lib/ssz_ex/error.ex
- lib/ssz_ex/merkleization.ex
- lib/ssz_ex/ssz_ex.ex
- lib/ssz_ex/utils.ex
- test/unit/ssz_ex_test.exs
This PR changes SSZ errors from strings to structs in order to add a stack trace in a future refactor.
Closes #1003
> refactor: change SSZ errors to structs

- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/beacon/store_setup.ex
- lib/types/deposit_tree_snapshot.ex
> feat: initialize testnet deposits from genesis state

- lib/lambda_ethereum_consensus/application.ex
Fixes a race condition where metadata is requested immediately after p2p is initialized, but metadata genserver is not yet ready.
> fix: switch order between metadata and beacon node processes

- config/runtime.exs
**Motivation**
Local testnets require ports to be configured so they don't collide with other local running nodes.
- Adds configuration in runtime.exs for discovery port.
Closes #810
> feat: make discovery port configurable

- .github/workflows/ci.yml
We're having [this reoccurring error](https://github.com/lambdaclass/lambda_ethereum_consensus/actions/runs/8838463470/job/24269689352?pr=1044). This PR fixes that and removes the unneeded setup-beam step on building the native libraries.
> fix: add hexpm mirror

- config/runtime.exs
First naive implementation where keystore.json is in one file and the password in a different file, similar to some local testnet setups.
Closes #1027
> feat: add keystore file and password file to runtime

- config/runtime.exs
This PR adds the `--boot-nodes` flag, which allows adding bootnodes from the CLI.
> feat: add boot-nodes flag

- lib/beacon_api/controllers/v1/node_controller.ex
- lib/beacon_api/router.ex
- test/unit/beacon_api/beacon_api_v1_test.exs
Adds the Beacon API `/eth/v1/node/health` endpoint. It will be used when integrating with kurtosis.
> feat: add health endpoint

- Dockerfile
This PR improves docker build caching by pre-compiling Rust NIFs and mix dependencies, before copying the whole repo.
> perf: improve Dockerfile caching

- config/runtime.exs
- lib/lambda_ethereum_consensus/beacon/beacon_chain.ex
- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/beacon/sync_blocks.ex
- lib/libp2p_port.ex
This PR adds a `--listen-address` flag that allows setting the addresses to listen on. It also fixes some edge-cases that happen when setting up a future network.
> feat: add `--listen-address` and fix edge-cases

- .dockerignore
- .github/workflows/ci.yml
- Dockerfile
When running the docker container, it emits warnings because we're redefining the protobuf-generated structs. This happens due to the output path being different from the repo, along with the `.dockerignore` not correctly ignoring generated files when copying.
> fix: protobuf warnings in container

- lib/lambda_ethereum_consensus/beacon/sync_blocks.ex
- lib/lambda_ethereum_consensus/p2p/peerbook.ex
- native/libp2p_port/internal/discovery/discovery.go
Closes #1033
This PR fixes the peer discovery spam in zero-latency scenarios issue that arose with the kurtosis integration. It also fixes a bug introduced in https://github.com/lambdaclass/lambda_ethereum_consensus/pull/1055/commits/327559c802acfab41db6be035baad7c24bef44bd, by subscribing to topics when skipping `SyncBlocks` fast-syncing.
> fix: reduce new peer notifications and subscribe to topics when skipping sync

- lib/keystore.ex
- test/unit/keystore_test.exs
**Motivation**
Validators can send key information in `pbkdf` format
> feat: add support for `pbkdf` in keystore.

- lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex
- lib/lambda_ethereum_consensus/store/state_db.ex
State pruning was not being triggered because checkpoint updates were occurring within the `on_tick` function, while only updates within the `on_block` function had been considered.
> fix: trigger pruning on tick

- lib/keystore.ex
- test/unit/keystore_test.exs
**Motivation**
There is not need to raise exception because of cheking pub keys [further](https://github.com/lambdaclass/lambda_ethereum_consensus/blob/ce09e953fe6fd12407fc0ec7b733e90e13d16b7c/lib/keystore.ex#L31)
Change `Map.fetch!(decoded_json, "pubkey") |> parse_binary!()` to 
```Elixir
pubkey =
case Map.has_key?(decoded_json, "pubkey") do
true -> Map.get(decoded_json, "pubkey") |> parse_binary!()
false -> derived_pubkey
end
```
+some tests added
Resolves #1084
Closes #1084
> refactor: make `pubkey` optional for `decoded_json` in `keystore` in `decode_str!` function

- lib/lambda_ethereum_consensus/validator/duties.ex
- lib/lambda_ethereum_consensus/validator/utils.ex
- lib/lambda_ethereum_consensus/validator/validator.ex
**Motivation**
Validator module is getting big and hard to follow. As part of a refactor of duties, I've extracted it into it's own module and added typespecs
> refactor: extract validator duties into its own module.

- docs/architecture.md
**Motivation**
We need to track all supervisors and other processes with their init args, so that we can fix the restart strategies as per #1097
> docs: add supervision tree graph and update the rest of the architecture document

- lib/lambda_ethereum_consensus/application.ex
**Motivation**
We had an error when calling GET /health the first couple of times.
Just change the order of how the app supervisor children are initialized.
Closes #1094
> fix: endpoint not available on GET /health

- lib/lambda_ethereum_consensus/validator/block_builder.ex
This PR fix a bug when building the block for slot 1.
The genesis block does not store the payload_block_hash and we were trying to access to a "null" value.
Closes #1087
> fix: bug when proposing on slot 1

- lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex
- lib/lambda_ethereum_consensus/store/store_db.ex
- lib/lambda_ethereum_consensus/telemetry.ex
- metrics/grafana/provisioning/dashboards/home.json
**Motivation**
In order to reduce complexity, we need to reduce concurrency as much as possible.
This PR removes the use of the `GenServer` state, storing it into the db, taking the first step towards removing the `GenServer` calls.
Additionally, it adds some metrics on store persisting and fetching:
Closes #1116 
Closes #1117
> refactor: persist forkchoice state

- bench/block_processing.exs
- bench/multiple_blocks_processing.exs
- lib/beacon_api/controllers/v2/beacon_controller.ex
- lib/beacon_api/helpers.ex
- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex
- lib/lambda_ethereum_consensus/fork_choice/handlers.ex
- lib/lambda_ethereum_consensus/fork_choice/head.ex
- lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex
- lib/lambda_ethereum_consensus/state_transition/state_transition.ex
- lib/lambda_ethereum_consensus/store/block_db.ex
- lib/lambda_ethereum_consensus/store/block_states.ex
- lib/lambda_ethereum_consensus/store/blocks.ex
- lib/lambda_ethereum_consensus/store/lru_cache.ex
- lib/lambda_ethereum_consensus/store/state_db.ex
- lib/lambda_ethereum_consensus/validator/block_builder.ex
- lib/lambda_ethereum_consensus/validator/validator.ex
- lib/types/block_info.ex
- lib/types/state_info.ex
- lib/types/store.ex
- test/integration/fork_choice/handlers_test.exs
- test/spec/runners/fork_choice.ex
- test/spec/runners/helpers/process_blocks.ex
- test/unit/beacon_api/beacon_api_v1_test.exs
- test/unit/beacon_api/beacon_api_v2_test.exs
- test/unit/block_states.exs
- test/unit/blocks.exs
- test/unit/validator/block_builder_test.exs
Changes:
- Add StateInfo struct/module with the root, block_root, and encoded fields to avoid recalculating them when storing and recovering when loading.
- Separate BlockInfo struct/module as it's growing a lot.
Next steps:
- Make LRU cache writes sequential (calls).
Closes #1133
> refactor: cache sequential writes

- lib/lambda_ethereum_consensus/p2p/metadata.ex
- lib/types/p2p/metadata.ex
- test/unit/metadata.exs
This PR persists the `GenServer` state of `Metadata` into the db.
Closes #1155
> refactor: persist Metadata state

- lib/lambda_ethereum_consensus/p2p/peerbook.ex
- lib/libp2p_port.ex
- Removes `:new_peer_handler` from `LibP2PPort` state.
- When a `NewPeer` notification arrives, invokes `Peerbook.new_peer_handler()` directly.
Closes #1161
> refactor: new_peer_handler as a function call

- lib/lambda_ethereum_consensus/application.ex
- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/p2p/metadata.ex
- lib/types/p2p/metadata.ex
- test/unit/beacon_api/beacon_api_v1_test.exs
- test/unit/metadata.exs
This PR removes all GenServer behavior from Metadata.
Also moves the db calls from `Types.Metadata` to `P2P.Metadata`.
Closes #1158
> refactor: remove GenServer behavior from Metadata

- lib/lambda_ethereum_consensus/beacon/beacon_node.ex
- lib/lambda_ethereum_consensus/p2p/peerbook.ex
- lib/libp2p_port.ex
- test/unit/libp2p_port_test.exs
- Replaces all `GenServer` casts and calls with function calls.
- Uses `KvSchema` behavior for db calls.
Closes #1170
> refactor: remove GenServer behavior from Peerbook

- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- test/unit/blocks.exs
- test/unit/pending_blocks.exs
Changes `PendingBlocks` to update the root of the block from `:download` to `:download_blobs` once downloaded.
Closes #1174
> fix: get_blocks_with_status

- docs/architecture.md
First iteration of validator documentation of current implementation.
> docs: add section for validators in architecture document

- lib/beacon_api/controllers/v1/beacon_controller.ex
- lib/beacon_api/helpers.ex
- lib/lambda_ethereum_consensus/store/block_by_slot.ex
- lib/lambda_ethereum_consensus/store/block_db.ex
- lib/lambda_ethereum_consensus/store/checkpoint_states_db.ex
- lib/lambda_ethereum_consensus/store/kv_schema.ex
- lib/types/types.ex
- test/fixtures/block.ex
- test/fixtures/utils.ex
- test/unit/store/block_by_slot_test.exs
- test/unit/store/block_db_test.exs
- test/unit/store/kv_schema_test.exs
Changes:
- Added `fold_keys` function + option to include the starting key in KvSchema.
- Added `BlockBySlot` module, implementing `KvSchema`. Includes tests.
- Implement an `all_present?` function in `BlockBySlot` to check if a range of slots has all blocks available.
- Made the BlockDb module use BlockBySlot instead of implementing all. Reduced code via KvSchema gets, puts, folds, removes.
- Added tests for BlockDb behaviors that require block by slot like pruning.
Part of #1207
> refactor: make BlockBySlot its own KvSchema

- docs/architecture.md
Adds execution chain section for architecture document. Includes:
- EngineAPI interactions: fork choice updates and payload validation.
- DepositContract tracking.
- Eth1Data vote.
> docs: add execution section in architecture document

- lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex
- lib/lambda_ethereum_consensus/metrics.ex
- lib/lambda_ethereum_consensus/state_transition/operations.ex
- lib/lambda_ethereum_consensus/state_transition/state_transition.ex
- lib/lambda_ethereum_consensus/telemetry.ex
- metrics/grafana/provisioning/dashboards/home.json
Metrics added in a hierarchy:
- handler: block processing, attestation processing, attester slashing.
- transition section: block vs epoch processing.
- operations: randao, attestation batch, withdrawals, etc.
Also added grafana panel with pie chart for execution times for each section. Might eventually move to span profiles if we introduce pyroscope.
Closes #1211
> feat: fork choice metrics

- lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
- lib/libp2p_port.ex
Changes:
- Makes `process_blocks` public in `PendingBlocks` 
- Calls `process_blocks` once at app startup in `Libp2pPort` at `handle_continue`, so pending blocks from prior executions are processed if considered recent.
Closes #1235
> fix: add a check for pending blocks at node startup

- lib/key_store_api/controllers/v1/key_store_controller.ex
- lib/keystore.ex
**Motivation**
The path generation for the Keystore files wasn't working.
- Use the encoded version of the `pubkey` to generate the path to the keystore file.
- `@keystore_dir` and `@keystore_pass_dir` were always set to the defaults values since they were being computed at compile time. Replace them with function calls to the `Keystore` module.
> fix: path generation

- .gitmodules
- Makefile
- README.md
- Adds Lambda's [ethereum-package](https://github.com/lambdaclass/ethereum-package/tree/lecc-integration) fork as a submodule.
- Updates the Makefile to use the submodule.
- Updates README.md
Closes #1270
> refactor: add ethereum-package as a submodule

- lib/lambda_ethereum_consensus/p2p/gossip/operations_collector.ex
- lib/lambda_ethereum_consensus/validator/block_builder.ex
- lib/lambda_ethereum_consensus/validator/duties.ex
**Motivation**
Fixing 2% block missed when proposing on 32 * n + 1 slot.
This PR fix the issue related to the Invalid signature error that we got on those particular slots. The problem is related to the parent root, we lacked a filter of contributions that doesn't match our parent root. This was happening at epoch boundaries because that's where we get a delay in the proposal and the second third kicks in before the notify head, which publish messages of the previous root, and make the aggregate become 0.
Resolves #1292
> fix: 2% blocks missed after sync aggregate addition

- lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex
- lib/lambda_ethereum_consensus/p2p/gossip/sync_committee.ex
- lib/lambda_ethereum_consensus/validator/duties.ex
- lib/lambda_ethereum_consensus/validator/validator_set.ex
- lib/types/att_subnet_info.ex
- lib/types/sync_subnet_info.ex
**Motivation**
Some messages from sync committees and attestations weren't part of their aggregates due to late subscribes to the subnets, this PR address it
This PR adds the subnets per slot to our shared duties and also adds a new key in the validator set struct to hold our last subnets subscribed to. On the first third of every slot, we check for the difference between the previous subnets and the new ones and do the appropriate unsubscribe/subscribe when needed. Apart from it this PR tackles an issue when receiving messages for non existing subnets crashed Libp2p.
Resolves #1300
Resolves #1301
> fix: avoid lost attestations and sync committee messages with early subnet subscribe

- lib/lambda_ethereum_consensus/execution/execution_chain.ex
- lib/lambda_ethereum_consensus/validator/block_builder.ex
- lib/types/deposit_tree.ex
- test/unit/deposit_tree_test.exs
**Motivation**
This errors were encountered on a long running session after passing the  `ChainSpec.get("SECONDS_PER_ETH1_BLOCK") * ChainSpec.get("ETH1_FOLLOW_DISTANCE")` slots threshold. 
This PR solved 4 issues, from lower to higher priority:
- The `has_majority?/2` calculation was not updating the votes past half of period, effectively this wasn't an issue, worst case another vote has also half of the votes totalling to the 100%, but it was pretty useful when debugging, adding it doesn't modify functionality.
- There were an old line of code trying to do a `List.last/1` on a MapSet, this was part of some previous refactor.
- The implementation of getting the first vote had some difference with the spec, it wasn't taking into account the previous eth1data when the …
> fix: eth1data votes error on block propose

- Makefile
- config/runtime.exs
- lib/lambda_ethereum_consensus/beacon/checkpoint_sync.ex
- lib/lambda_ethereum_consensus/p2p/peerbook.ex
**Motivation**
This is a small PR that makes the node run differently on sepolia and mainnet related to peer scoring, making it fastest in mainnet to remove peers.
This PR adds a couple of things:
- A config to match penalizing score given the network
- A small fix of a match that caused troubles sometimes in Holesky at node startup
- Added an extra parameter to the make tasks for starting the node to allow them to start multiple nodes easily in the same machine
> chore: peerbook penalization config + node start fix

- .github/workflows/assertoor.yml
**Motivation**
Kurtosis moved from 1.3.1 to 1.4.0 and our checks started failing when loading the kurtosis engine
This PR fixes kurtosis version to the latest working one: 1.3.1
> fix: fixed kurtosis image to 1.3.1, 1.4.0 breaks kurtosis engine startup

- .github/workflows/assertoor.yml
- assertoor-config.yml
**Motivation**
Assertoor step is failing due to versions not fixed (this was already don on ethrex)
Even if we just have the skeleton of the assertoor integration, improver versions make the step to fail,. this solves it.
> chore(core): assertoor version fixes

- test/unit/beacon_api/beacon_api_v1_test.exs
Fix a leaky test when the order of test change and the store didn't had genesis in it
> fix: leaky test missing genesis time in store mock

- lib/lambda_ethereum_consensus/fork_choice/head.ex
**Motivation**
Running the node for more than an epoch and just after block processing, 20+ seconds were taken before finishing the fork choice step, which made it impossible to execute sequentially inside the slot range (12s)
After extensive debugging, the issue was found in the recompute head calculation, specially in the repeatedly call of get_weight where it wasn't really needed (outside of forks). The solution was taking into account this cases and stop calculating get_weight when encountered. 
Resolves #1381
> fix: recompute head was taking more than 20s in mainnet

- .tool-versions
**Motivation**
In a previous PR the go version was set to 1.22, but it lacked the patch version resulting in a 404 while trying to install. Protobuff was also updated.
> fix: change tools versions with a correct version of go

- lib/lambda_ethereum_consensus/state_transition/accessors.ex
**Motivation**
In #1419 the link check is not passing because of a too deeply nested function this PR fixes that
Move the calculation of committee_attesters to its own function
> refactor: move committee_attesters calculation to own function

- test/spec/runners/bls.ex
- test/spec/runners/epoch_processing.ex
- test/spec/runners/finality.ex
- test/spec/runners/fork_choice.ex
- test/spec/runners/kzg.ex
- test/spec/runners/light_client.ex
- test/spec/runners/operations.ex
- test/spec/runners/random.ex
- test/spec/runners/rewards.ex
- test/spec/runners/sanity.ex
- test/spec/runners/shuffling.ex
- test/spec/runners/ssz_generic.ex
- test/spec/runners/ssz_static.ex
- test/spec/runners/sync.ex
**Motivation**
We were skipping 8k spec-test before this PR
After some debugging and testing, most of the previously skipped test are not needed to be skipped at all. We are right now at 784 spect-test skipped which is mostly the same number as we are currently skipping in main.
This nonetheless could include some false positives and it's possible tat lots of this test share low-hanging fruit fixes apart from the electra implementation. I created a new issue for tracking that: #1429
Before this PR:
`11370 tests, 206 failures, 8092 skipped`
After this PR:
`11370 tests, 2003 failures, 784 skipped`
> fix: skipped spec tests in electra

- native/ssz_nif/src/utils/mod.rs
**Motivation**
After #1427 nearly 1500 test were failing due to ssz issues
This PR makes a small changing adding the new containers to the schema_match macro that were missing them.
Before this PR: 
`11370 tests, 2003 failures, 784 skipped`
After this PR:
`11370 tests, 979 failures, 784 skipped`
Resolves part of #1429
> fix: new ssz fixes for the static spec-test

- .github/workflows/ci.yml
- .github/workflows/ci_skipped.yml
- .tool-versions
- Dockerfile
- test/unit/validator/block_builder_test.exs
**Motivation**
Most of CI steps where failing unable to fetch the protobuf-compiler
All go version has been updated to 1.24 and all Ubuntu 22.04 to 24.04 (LTS)
> fix: fixing the CI updating ubuntu and go

- .github/config/assertoor/cl-stability-check.yml
- .github/config/assertoor/network-params.yml
- .github/workflows/assertoor.yml
- Makefile
- lib/beacon_api/controllers/v1/config_controller.ex
- network_params.yaml
**Motivation**
PRs were failing in main due to assertoor (and specifically the update of `ethereum-package`)
This PR updates kurtosis version as well as the clients one, it doesn't add the `electra_fork_epoch` param to still run in `deneb`.
The PR also add some minor changes, it fixed some hex values in the config matching the variables ending as `FORK_VERSION`, to avoid listing the new ones added in `ethereum-package` one by one and adds a convenient way to run assertoor locally.
> chore: update to the latest version of kurtosis

- electra-gap.md
**Motivation**
Update the `electra-gap.md` to show our roadmap and easily visualize the current status
> docs: `electra-gap.md` enhancement with roadmap and current status

- .github/config/assertoor/cl-stability-check.yml
- .github/config/assertoor/network-params.yml
**Motivation**
Until #1413 assertoor will just validate that nodes are healthy.
This PR disable all other checks apart from the initial health ones.
> chore: disable assertoor failing checks
